version: "3.8"

services:
  email:
    container_name: email-service
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: python ./app.py 0.0.0.0:85
    ports:
      - "14000:85"
    volumes:
      - .:/appbizion
    environment:
      FLASK_DEBUG: development
    networks:
      - email-postgres
networks:
  email-postgres:
    name: email-postgres
    driver: bridge
volumes:
  pgdata:
  