version: "3.8"

services:
  email:
    container_name: email-service
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: python ./app.py 0.0.0.0:85
    ports:
      - "9000:85"
    volumes:
      - .:/appbizion
    environment:
      FLASK_DEBUG: development
    networks:
      - email-postgres
  postgres:
    image: postgres:12-bullseye
    container_name: postgres_email
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=3g8tss955
      - POSTGRES_DB=CormagoContact
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - email-postgres
networks:
  email-postgres:
    name: email-postgres
    driver: bridge
volumes:
  pgdata:
  